---
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

# Market Cool-Down Insights

<h3 style="color:grey;">2023 Q4 International Housing Report</h3>

### Executive Summary

**Housing affordability reaches new heights amidst market cooldown.** As we wrap up 2023, the global housing market has seen a notable decrease in house prices, enhancing overall affordability compared to the previous year. This trend is driven by the coordinated efforts of central banks globally to hike interest rates, effectively targeting inflation, and exerting downward pressure on property prices. Simultaneously, strategic government interventions via tax benefits and financial supports have alleviated some cost burdens for households. However, the ongoing challenges of sticky inflation, wage dynamics, slowing global activity, trade vulnerabilities, high debt levels, and geopolitical and technological uncertainties pose complex risks that could unpredictably sway future housing market trajectories.

### Economic Indicators

**Central banks’ policies stabilize, nudging inflation towards targets.** In a strategic divergence, advanced economies have frozen their [policy rates](https://www.dallasfed.org/research/international/dgei/policy) while emerging markets have reduced the pace of hikes, some even cutting rates modestly. This policy environment has ushered in the highest short-term interest rates seen in two decades. Despite a reduction in the pace of hikes, [long-term interest rates](https://www.dallasfed.org/research/international/dgei/ltrates) ended 2023 on a downward trajectory. Most central banks appear well-aligned to bring [inflation](https://www.dallasfed.org/research/international/dgei/cpi) back to their respective targets after a significant downtrend that began in late 2022. Although global demand weakness has dampened overall economic activity, contributing to subdued [growth](https://www.dallasfed.org/research/international/dgei/gdp) in late 2023, the United States stands out with a robust labor market that continues to underpin its economic resilience.

### Global Property Prices and Trends

#### Decline in Global Prices

Global real property prices dropped by -0.9% showing momentum of a negative growth path. Since the peak of 2022Q2, real house prices have decreased continuously only with one positive rebound in 2023Q2. This quarter, Croatia and Denmark experienced higher growth rates (+2.5% and +1.2%, respectively), whereas prices in Canada, Luxembourg, Norway, France, and Germany declined (-5.1%, -3.5%, -2.5%, -2.1% and -2.1%, respectively). In the US (-0.2%) and the UK (-0.25%) prices slipped slightly. Annual figures support the downward trend of real housing prices: global prices contracted by -3.6% in 2023 compared to an increase of +4.5% in 2022.

#### Enhanced Global Affordability

Global affordability as measured by the real house price-to-income ratio decreased by -0.9%, signaling more affordable housing. In 2023Q4, real personal income increased slightly to +0.1%, which, coupled with falling property prices, made housing more accessible. When looking at the specific countries, the picture remains similar: countries with the largest increases in house prices suffer from the largest reduction in affordability and vice versa. One of the few exceptions is Spain, where house prices dropped slightly (-0.2%) yet personal income decreased the most out of our pool of countries (-1.6%). Hence, despite decreasing prices housing became less affordable. In 2023 housing was more affordable (-4% house price-to-income ratio) than in 2022 (+7.4%).

#### Mortgage and Rental Pressures

Amidst a tight monetary policy landscape, mortgage rates have climbed, placing additional financial stress on households with adjustable-rate mortgages. The duration of high interest rates will reveal the full extent of the impact of monetary policy on the housing market for those countries with stronger transmission channels, especially as mortgage rates reset. Rental prices are accelerating relative to last quarter with Canada, Belgium, and Denmark experiencing the largest upsurges in rents (+1.6%, +1.3% and +1.1%, respectively). The US and the UK also experienced an uptick in rents with quarterly increases of +0.95% and +0.7%. On the other side of the spectrum, the largest decrease in rental price pressures was in the Republic of Korea reaching almost a -1% drop in prices.is may provide some breathing room for homeowners with adjustable mortgage rates in the future.

### Selected Housing Government Policies and Regulations

**United Kingdom:** The Government introduced new regulations to ensure that Houses in Multiple Occupations (HMO) are considered a single dwelling for council tax, with the owner being the liable person. This regulation will simplify administration for landlords and reduce costs for tenants. 

**Canada:** The Government proposed a legislation to remove temporarily the Goods and Services Tax (GST) on new rental construction and increase the GST rental rebate from 36% to 100% for apartment buildings, student housing, and senior residences. The purpose of the bill is to increase housing supply and affordability.

**Australia:** The Government passed the Help to Buy bill that establishes a shared equity scheme assisting low to middle-income earners purchase new or existing homes. The Commonwealth contributes a portion of the equity (up to 40%) to reduce upfront costs for eligible buyers.

**Germany:** The Government decided to postpone stricter building insulation criteria and replacing fossil fuel heating systems in new homes. This relaxation aims to address concerns from the construction industry regarding rising costs and a potential slowdown in housing construction.

